# https://serenest.academy
[build]
  publish = "static"
  command = "echo Static site ready"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "https://www.serenest.academy/*"
  to = "https://serenest.academy/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://serenest.academy/*"
  to = "https://serenest.academy/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.serenest.academy/*"
  to = "https://serenest.academy/:splat"
  status = 301
  force = true
